### ISSUE TITLE
Dataloader with mesh from scene

### ISSUE THREAD

**Issue by yihao19** [cheind/pytorch-blender#27]
I am wondering if it is possible to make dataloader return the actual mesh I created instead of the image?

**Comment by cheind** [comment]
Yes, that should work ... it hasn't been done, but you would just need to pass along the mesh vertices / faces from blender. 

If you take this example and line https://github.com/cheind/pytorch-blender/blob/a5b819f04ff5c7145b7164b48abd1a3fe69f0db4/examples/compositor_normals_depth/compositor_normals_depth.blend.py#L23 you would need to publish the mesh instead of the image. The publisher should be able to send around any pickleable object: https://github.com/cheind/pytorch-blender/blob/develop/pkg_blender/blendtorch/btb/publisher.py

**Comment by yihao19** [comment]
Thank you
